// vue-app/src/App.vue
<script>
import Navbar from "./components/Navbar.vue";
import Hero from "./components/Hero.vue";
import Skills from "./components/Skills.vue";
import ProjectsList from "./components/ProjectsList.vue";

export default {
  components: {
    Navbar,
    Hero,
    Skills,
    ProjectsList,
  },
};
</script>

<template>
  <Navbar />

  <main>
    <Hero />

    <Skills />

    <ProjectsList />
  </main>
</template>

// svelte-app/src/App.svelte
<script>
  import Hero from "./lib/components/Hero.svelte";
  import Navbar from "./lib/components/Navbar.svelte";
  import ProjectsList from "./lib/components/ProjectsList.svelte";
  import Skills from "./lib/components/Skills.svelte";
</script>

<Navbar />

<main>
  <Hero />

  <Skills />

  <ProjectsList />
</main>
