// react-app/src/components/Navbar/Navbar.jsx
import React, { useState } from "react";
import styles from "./Navbar.module.css";
import { FaBars } from "react-icons/fa";
import { RxCross2 } from "react-icons/rx";

const navbarItems = [
  { title: "About", path: "#about" },
  { title: "Skills", path: "#skills" },
  { title: "Projects", path: "#projects" },
  { title: "Contact", path: "#contact" },
];

export default function Navbar() {
  const [isOpen, setIsOpen] = useState(false);

  const scrollToLocation = (event, path) => {
    event.preventDefault();
    const element = document.querySelector(path);
    if (element) {
      element.scrollIntoView({
        behavior: "smooth",
        block: "center",
        inline: "nearest",
      });
    }
    setIsOpen(!isOpen);
  };

  return (
    <>
      <nav className={styles.container}>
        <div className={styles.container.left}>
          <span>Tomas Oh</span>
        </div>
        <div className={styles.right}>
          <div className={`${styles.sections} ${isOpen && styles.active}`}>
            <button
              onClick={() => setIsOpen(!isOpen)}
              className={styles.closeNavbarBtn}
            >
              <RxCross2 />
            </button>
            {navbarItems.map((item, index) => (
              <span key={index} onClick={(e) => scrollToLocation(e, item.path)}>
                {item.title}
              </span>
            ))}
          </div>
          <button
            onClick={() => setIsOpen(!isOpen)}
            className={styles.openNavbarBtn}
          >
            <FaBars />
          </button>
        </div>
      </nav>

      <div
        onClick={() => setIsOpen(!isOpen)}
        className={`${styles.darkCover} ${isOpen && styles.activeCover}`}
      />
    </>
  );
}

// angular-app/src/app/features/navbar/navbar.component.ts
import { CommonModule } from "@angular/common";
import { Component } from "@angular/core";

@Component({
  selector: "app-navbar",
  standalone: true,
  imports: [CommonModule],
  templateUrl: "./navbar.component.html",
  styleUrls: ["./navbar.component.css"],
})
export class NavbarComponent {
  isOpen: boolean = false;
  navbarItems: NavbarItem[] = [
    { title: "About", path: "#about" },
    { title: "Skills", path: "#skills" },
    { title: "Projects", path: "#projects" },
    { title: "Contact", path: "#contact" },
  ];

  scrollToLocation(event: Event, path: string) {
    event.preventDefault();
    const element = document.querySelector(path);
    if (element) {
      element.scrollIntoView({
        behavior: "smooth",
        block: "center",
        inline: "nearest",
      });
    }
    this.isOpen = !this.isOpen;
  }
}

export interface NavbarItem {
  title: string;
  path: string;
}

<nav class="container">
  <div class="left">
    <span>Tomas Oh</span>
  </div>
  <div class="right">
    <div [ngClass]="{ sections: true, active: isOpen }">
      <button class="closeNavbarBtn" (click)="isOpen = !isOpen">YYOOOOO</button>
      <span
        *ngFor="let item of navbarItems"
        (click)="scrollToLocation($event, item.path); isOpen = !isOpen"
      >
        {{ item.title }}
      </span>
    </div>
    <button class="openNavbarBtn"></button>
  </div>
</nav>
