// react-app/src/components/Hero/Hero.jsx
import React from "react";
import styles from "./Hero.module.css";
import headshot from "/assets/website/photo.jpg";

export default function Hero() {
  return (
    <section className={styles.hero}>
      <div className={styles.left}>
        <h3 id="about">Hello! I'm</h3>
        <h1>
          <span className={styles.blue}>Tomas Oh</span>
        </h1>
        <h2>
          Full-Stack Software Engineer and Computer Science Student at
          California State University, Fullerton
        </h2>

        <p>
          Strong passion for developing curated sofware and learning new
          technologies every day. I believe in giving opportunities to try new
          things, working outside my comfort zone, and expanding my knowledge
          and perception of tomorrow's betterment.
        </p>
        <p>
          My other interests include watching Soccer, playing competitive Smash
          Bros, and drawing!
        </p>
      </div>
      <div className={styles.right}>
        <img src={headshot} alt="Headshot Photo" />
      </div>
    </section>
  );
}

// angular-app/src/app/features/hero/hero.component.ts
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
// import photo from "../../../assets/website/photo.jpg";

@Component({
  selector: "app-hero",
  standalone: true,
  imports: [CommonModule],
  templateUrl: "./hero.component.html",
  styleUrls: ["./hero.component.css"],
})
export class HeroComponent {
  // headshot = photo;
}

<section class="hero">
  <div class="left">
    <h3 id="about">Hello! I'm</h3>
    <h1>
      <span class="blue">Tomas Oh</span>
    </h1>
    <h2>
      Full-Stack Software Engineer and Computer Science Student at California
      State University, Fullerton
    </h2>

    <p>
      Strong passion for developing curated sofware and learning new
      technologies every day. I believe in giving opportunities to try new
      things, working outside my comfort zone, and expanding my knowledge and
      perception of tomorrow's betterment.
    </p>
    <p>
      My other interests include watching Soccer, playing competitive Smash
      Bros, and drawing!
    </p>
  </div>
  <div class="right">
    <img src="assets/website/photo.jpg" alt="Headshot" />
  </div>
</section>
