// angular-app/src/app/features/project/project.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-project',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './project.component.html',
  styleUrls: ['./project.component.css']
})
export class ProjectComponent {

}

<div class="projectContainer">
  <h3>{{ project.name }}</h3>
  <img
    class="image"
    src="{project.imageSource}"
    [alt]="'Image for Project ' + project.name"
  />
  <div class="techStackContainer">
    <app-badge
      *ngFor="let technology of project.techStack"
      [text]="technology"
    />
  </div>
  <p>{{ project.description }}</p>
  <div class="links">
    <app-button *ngIf="project.demoLink !== ''">
      <a class="link" [href]="project.demoLink">Demo</a>
    </app-button>
    <app-button>
      <a class="link" [href]="project.githubLink"> Github Repo </a>
    </app-button>
  </div>
</div>

// react-app/src/components/Project/Project.jsx
import React from "react";
import styles from "./Project.module.css";
import Badge from "../Badge/Badge";
import Button from "../Button/Button";

export default function Project(props) {
  return (
    <div className={styles.projectContainer}>
      <h3>{props.projectName}</h3>
      <img
        className={styles.image}
        src={props.imageSource}
        alt={"Image for Project " + props.projectName}
      />
      <div className={styles.techStackContainer}>
        {props.projectTechStack.map((technology, key) => (
          <Badge key={key} text={technology} />
        ))}
      </div>
      <p>{props.projectDescription}</p>
      <div>
        <Button>
          <a className={styles.link} href={props.demoLink}>
            Demo
          </a>
        </Button>
        <Button>
          <a className={styles.link} href={props.githubLink}>
            Github Repo
          </a>
        </Button>
      </div>
      <div className={styles.links}></div>
    </div>
  );
}
