// react-app/src/App.jsx
import { useState } from "react";
import Navbar from "./components/Navbar/Navbar";
import Hero from "./components/Hero/Hero";
import Skills from "./components/Skills/Skills";
import ProjectsList from "./components/ProjectsList/ProjectsList";

function App() {
  return (
    <>
      <Navbar />

      <main>
        <Hero />
        {/* Displays my programming/framework skills */}
        <Skills />

        <ProjectsList />
      </main>
    </>
  );
}

export default App;

// vue-app/src/App.vue
<script>
import Navbar from "./components/Navbar.vue";
import Hero from "./components/Hero.vue";
import Skills from "./components/Skills.vue";
import ProjectsList from "./components/ProjectsList.vue";

export default {
  components: {
    Navbar,
    Hero,
    Skills,
    ProjectsList,
  },
};
</script>

<template>
  <Navbar />

  <main>
    <Hero />

    <Skills />

    <ProjectsList />
  </main>
</template>
