// react-app/src/components/Skills/Skills.jsx
import React from "react";
import styles from "./Skills.module.css";

export default function Skills() {
  const programmingSkills = [
    "cpp",
    "python",
    "typescript",
    "javascript",
    "html",
    "css",
    "java",
  ];

  const frameworkSkills = [
    "react",
    "next",
    "node",
    "svelte",
    "sass",
    "tailwind",
  ];

  return (
    <section className={styles.skillsSection}>
      <h2 className={styles.sectionTitle}>Skills</h2>
      <div className={styles.skillsContainer}>
        <h3 className={styles.sectionSubtitle}>Programming</h3>
        <div>
          {programmingSkills.map((skill, key) => {
            return (
              <img
                key={key}
                src={`/assets/skills/${skill}-icon.png`}
                alt={skill + " icon"}
              />
            );
          })}
        </div>
      </div>
      <div className={styles.skillsContainer}>
        <h3 className={styles.sectionSubtitle}>Frameworks</h3>
        <div>
          {frameworkSkills.map((skill, key) => {
            return (
              <img
                key={key}
                src={`/assets/skills/${skill}-icon.png`}
                alt={skill + " icon"}
              />
            );
          })}
        </div>
      </div>
    </section>
  );
}

// angular-app/src/app/features/skills/skills.component.ts
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "app-skills",
  standalone: true,
  imports: [CommonModule],
  templateUrl: "./skills.component.html",
  styleUrls: ["./skills.component.css"],
})
export class SkillsComponent {
  programmingSkills: string[] = [
    "cpp",
    "python",
    "typescript",
    "javascript",
    "html",
    "css",
    "java",
  ];

  frameworkSkills: string[] = [
    "react",
    "next",
    "node",
    "svelte",
    "sass",
    "tailwind",
  ];
}

<section class="skillsSection">
  <h2 id="skills" class="sectionTitle">Skills</h2>
  <div class="skillsContainer">
    <h3 class="sectionSubtitle">Programming</h3>
    <div>
      <img
        *ngFor="let skill of programmingSkills"
        [src]="'/assets/skills/' + skill + '-icon.png'"
        [alt]="skill + 'icon'"
      />
    </div>
  </div>
  <div class="skillsContainer">
    <h3 class="sectionSubtitle">Frameworks</h3>
    <div>
      <img
        *ngFor="let skill of frameworkSkills"
        [src]="'/assets/skills/' + skill + '-icon.png'"
        [alt]="skill + 'icon'"
      />
    </div>
  </div>
</section>
